include /etc/openldap/schema/core.schema
include /etc/openldap/schema/cosine.schema
include /etc/openldap/schema/inetorgperson.schema
include /etc/openldap/schema/nis.schema

pidfile /run/slapd/slapd.pid
argsfile /run/slapd/slapd.args

# Specify the module path
modulepath /usr/lib/openldap
moduleload back_mdb

database mdb
maxsize 1073741824
suffix "dc=example,dc=com"
rootdn "cn=admin,dc=example,dc=com"
rootpw {SSHA}your_hashed_password_here
directory /var/lib/openldap

index objectClass eq
index cn,sn,uid,mail eq,pres,sub